authentication/urls.py
from django.urls import path
from authentication.views import *

app_name = 'authentication'

urlpatterns = [
    path('login', login_user, name='login'),
    path('register', register_user, name='register'),
    path('logout', logout_user, name='logout'),
    path('flutter-login/', login_flutter, name='flutter_login'),
    path('flutter-register/', register_flutter, name='flutter_register'),
    path('flutter-logout/', logout_flutter, name='flutter_logout'),
]

gamehunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search.urls')),
    path('admin/', admin.site.urls),
    path('display/', include('display.urls')),
    path('search/', include('search.urls')),
    path('review/', include('review.urls')),
    path('news/', include('news.urls')),
    path('authentication/', include('authentication.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('wishlist/', include('wishlist.urls')),
]

news/urls.py
from django.urls import path
from .views import show_news, edit_news, create_news, home_news, delete_news
from .views import show_xml, show_json, show_xml_by_id, show_json_by_id
from .views import create_news_flutter, edit_news_flutter, delete_news_flutter

app_name = 'news'

urlpatterns = [
    path('', home_news, name='home_news'),
    path('<uuid:id>', show_news, name='show_news'),
    path('create-news/', create_news, name='create_news'),
    path('edit-news/<uuid:id>', edit_news, name='edit_news'),
    path('delete/<uuid:id>', delete_news, name='delete_news'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('create-flutter/', create_news_flutter, name='create_news_flutter'),
    path('edit-flutter/<uuid:id>/', edit_news_flutter, name='edit_news_flutter'),
    path('delete-flutter/<uuid:id>/', delete_news_flutter, name='delete_news_flutter'),
]

search/urls.py
from django.urls import path
from search.views import show_search,show_json,delete_game,add_game_entry_ajax,show_json_by_id, edit_game_ajax,create_game_flutter, edit_game_flutter, delete_game_flutter, game_list_json,get_user_role

app_name = 'search'

urlpatterns = [
    path('', show_search, name='show_search'),
    path('json/', show_json, name='show_json'),
    path('delete/<uuid:id>', delete_game, name='delete_game'),
    path('create-game-entry-ajax', add_game_entry_ajax, name='add_game_entry_ajax'),
    path('json/<uuid:id>', show_json_by_id, name='show_json'),
    path('edit-game-ajax/<uuid:id>', edit_game_ajax, name = 'edit_game_ajax'),
    path('create-game-flutter/', create_game_flutter, name='create_mood_flutter'),
    path('edit-game-flutter/<uuid:game_id>/', edit_game_flutter, name='edit_game_flutter'),
    path('delete-game-flutter/<uuid:game_id>/', delete_game_flutter, name='delete_game_flutter'),
    path('search/json/', game_list_json, name='game_list_json'),
    path('user-role/', get_user_role, name='get_user_role'),
]

userprofile/urls.py
from django.urls import path
from userprofile.views import *

app_name = 'userprofile'

urlpatterns = [
    path('userprofile', show_user_profile_page, name='userprofile'),    
    path('userprofiel/update', update_user_profile, name="update_user_profile"),
    path('userprofile/get', get_user_profile, name="get_user_profile"),
    path('userprofile/update-flutter', update_user_profile_flutter, name="update_user_profile_flutter")
]

wishlist/urls.py
from django.urls import path
from wishlist.views import view_wishlist, delete_wishlist, create_wishlist, show_json, add_wishlist_ajax, get_wishlist_ajax, delete_wishlist_flutter

app_name = 'wishlist'

urlpatterns = [
    path('', view_wishlist, name='view_wishlist'),
    path('delete-wishlist/<uuid:id>/', delete_wishlist, name='delete_wishlist'),
    path('json/', show_json, name='show_json'),
    path('create-wishlist/<uuid:game_id>/', create_wishlist, name='create_wishlist'),
    path('add-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_ajax, name='get_wishlist'),
    path('delete-wishlist-flutter/<uuid:id>/', delete_wishlist_flutter, name='delete_wishlist_flutter')
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% block meta %}
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1">
    {% endblock meta %}
    <script src="https://cdn.tailwindcss.com">
    </script>
    <link rel="stylesheet" href="{% static 'css/global.css' %}">
  </head>

  <body>
    {% block content %} {% endblock content %}
    {% include 'navbar.html' %}
  </body>
</html>

templates/navbar.html
{% load static %} 
<nav class="fixed top-0 w-full bg-red-500 text-white p-4">
    <div class="container mx-auto flex justify-between items-center">
        <div class="flex items-center space-x-4">
            <a href="{% url 'search:show_search' %}" class="flex items-center space-x-2">
                <img src="{% static 'image/logo.png' %}" alt="Logo" href="{% url 'search:show_search' %}" class="w-8 h-8">
                <span class="text-xl font-semibold">GameHunt</span>
            </a>

            <div class="hidden md:flex space-x-6">
                <!-- Apply hover to change background and text color -->
                <a href="{% url 'news:home_news' %}" class="px-3 py-2 rounded hover:bg-red-700 hover:text-gray-400">News</a>
                <a href="{% url 'search:show_search' %}" class="px-3 py-2 rounded hover:bg-red-700 hover:text-gray-400">Browse Games</a>
                <a href="{% url 'wishlist:view_wishlist' %}" class="px-3 py-2 rounded hover:bg-red-700 hover:text-gray-400">Wishlist</a>
            </div>
        </div>

        <div class="relative">
            <!-- Apply hover to user menu button to change background and text color -->
            <button id="userMenuButton" class="flex items-center space-x-2 px-3 py-2 rounded hover:bg-red-700 hover:text-gray-400 focus:outline-none">
                <img src="{% static 'image/user_icon.png' %}" alt="User Icon" class="w-6 h-6">
                <span class="text-sm">{{ request.user.username }}</span>
                <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
                </svg>
            </button>

            <div id="userDropdown" class="z-50 hidden absolute right-0 mt-2 w-48 bg-white text-black border border-gray-300 py-2">
                <a href="{% url 'userprofile:userprofile' %}" class="block px-4 py-2 text-sm hover:bg-soft-red hover:text-gray-400">Edit Profile</a>
                <a href="{% url 'authentication:logout' %}" class="block w-full text-left px-4 py-2 text-sm hover:bg-soft-red hover:text-gray-400">Logout</a>

            </div>
        </div>
    </div>
</nav>

<script>
    document.getElementById('userMenuButton').addEventListener('click', function(event) {
        event.stopPropagation();
        var dropdown = document.getElementById('userDropdown');
        dropdown.classList.toggle('hidden');
    });

    window.addEventListener('click', function(event) {
        var dropdown = document.getElementById('userDropdown');
        if (!event.target.closest('#userMenuButton') && !event.target.closest('#userDropdown')) {
            dropdown.classList.add('hidden');
        }
    });
</script>