gamehunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search.urls')),
    path('admin/', admin.site.urls),
    path('display/', include('display.urls')),
    path('search/', include('search.urls')),
    path('review/', include('review.urls')),
    path('news/', include('news.urls')),
    path('authentication/', include('authentication.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('wishlist/', include('wishlist.urls')),
]

news/urls.py
from django.urls import path
from .views import show_news, edit_news, create_news, home_news, delete_news
from .views import show_xml, show_json, show_xml_by_id, show_json_by_id
from .views import create_news_flutter, edit_news_flutter, delete_news_flutter

app_name = 'news'

urlpatterns = [
    path('', home_news, name='home_news'),
    path('<uuid:id>', show_news, name='show_news'),
    path('create-news/', create_news, name='create_news'),
    path('edit-news/<uuid:id>', edit_news, name='edit_news'),
    path('delete/<uuid:id>', delete_news, name='delete_news'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('create-flutter/', create_news_flutter, name='create_news_flutter'),
    path('edit-flutter/<uuid:id>/', edit_news_flutter, name='edit_news_flutter'),
    path('delete-flutter/<uuid:id>/', delete_news_flutter, name='delete_news_flutter'),
]

news/models.py
from django.db import models
import uuid

# Create your models here.

class News(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    title = models.CharField(max_length=255)
    article = models.TextField()
    author = models.CharField(max_length=255)
    # Automatically sets the creation date
    # post_date = models.DateTimeField(auto_now_add=True)
    # Automatically updates the field on each save
    update_date = models.DateTimeField(auto_now=True)

    

news/forms.py
from django.forms import ModelForm
from django import forms
from .models import News
from django.utils.html import strip_tags

class NewsForm(ModelForm):
    class Meta:
        model = News
        fields = ["title", "article", "author", 
                  ]
        widgets = {
            'title': forms.TextInput(attrs={
                'class': 'form-input', 
                'placeholder': 'Enter news headline'
                }),
            'article': forms.Textarea(attrs={
                'class': 'form-input', 
                'placeholder': 'Write your article here...'
                }),
            'author': forms.TextInput(attrs={
                'class': 'form-input', 
                'placeholder': 'Enter news author'
                }),
            }

    def clean_news_title(self):
        title = self.cleaned_data["title"]
        return strip_tags(title)

    def clean_article(self):
        article = self.cleaned_data["article"]
        return strip_tags(article)
    
    def clean_author(self):
        author = self.cleaned_data["author"]
        return strip_tags(author)

news/views.py
from django.shortcuts import render, reverse
from .forms import NewsForm
from .models import News
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt
import json
from django.http import JsonResponse

# Create your views here.
@login_required
def home_news(request):
    if request.user.is_superuser:
        role = 'admin'
    else:
        role = 'user'
    context = {
        'role' : role,
    }
    return render(request, "home_news.html", context)

def show_news(request, id):
    news = News.objects.get(pk = id)
    if request.user.is_superuser:
        role = 'admin'
    else:
        role = 'user'
    context = {
        'role' : role,
        'title' : news.title,
        'author' : news.author,
        'article' : news.article,
        # 'post_date' : news.post_date,
        'update_date' : news.update_date,
        'pk' : news.pk,
        'news_entries' : News.objects.all()
    }
    return render(request, "news.html", context)

def create_news(request):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You do not have permission to perform this action.")
   
    form = NewsForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        news_entry = form.save(commit=False)
        news_entry.user = request.user
        news_entry.save()
        return HttpResponseRedirect(reverse('news:home_news'))
        # return redirect('news:home_news.html')

    context = {'form': form}
    return render(request, "create_news.html", context)

def edit_news(request, id):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You do not have permission to perform this action.")
    
    # Get news entry berdasarkan id
    news = News.objects.get(pk = id)

    # Set news entry sebagai instance dari form
    form = NewsForm(request.POST or None, instance=news)

    if form.is_valid() and request.method == "POST":
        # Simpan form dan kembali ke halaman awal
        form.save()
        return HttpResponseRedirect(reverse('news:home_news'))

    context = {'form': form}
    return render(request, "edit_news.html", context)

def delete_news(request, id):
    if not request.user.is_superuser:
        return HttpResponseForbidden("You do not have permission to perform this action.")
    
    # Get news berdasarkan id
    news = News.objects.get(pk = id)
    # Hapus news
    news.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('news:home_news'))

def show_xml(request):
    data = News.objects.all()
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    data = News.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = News.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = News.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
def create_news_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)
        new_mood = News.objects.create(
            # user=request.user,
            title=data["title"],
            author=data["author"],
            article=data["article"],
            update_date=data["update_date"],
        )

        new_mood.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)
    

@csrf_exempt
def edit_news_flutter(request, id):
    # news_id adalah UUID dalam bentuk string
    if request.method == 'PUT':
        try:
            data = json.loads(request.body)
            # news_uuid = UUID(news_id)
            news = News.objects.get(id=id)

            if "title" in data: news.title = data["title"]
            if "article" in data: news.article = data["article"]
            if "author" in data: news.author = data["author"]
            if "update_date" in data: news.update_date = data["update_date"]

            news.save()

            return JsonResponse({"status": "success"}, status=200)
        except News.DoesNotExist:
            return JsonResponse({"status": "error", "message": "News not found"}, status=404)
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)


@csrf_exempt
def delete_news_flutter(request, id):
    if request.method == 'DELETE':
        try:
            # news_uuid = UUID(news_id)
            news = News.objects.get(pk=id)
            news.delete()
            return JsonResponse({"status": "success"}, status=200)
        except News.DoesNotExist:
            return JsonResponse({"status": "error", "message": "News not found"}, status=404)
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)

news/templates/create_news.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add News</title>
{% endblock meta %}

{% block content %}

<div class="mt-20 form-container">
  <div class="form-header">Add News</div>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for field in form %}
      <div class="form-group">
        <label class="form-label">{{ field.label }}:</label>
        {{ field }}
        {{ field.errors }}
      </div>
    {% endfor %}

    <button type="submit" class="submit-button">Add News</button>
  </form>
</div>

{% endblock %}

news/templates/edit_news.html
{% extends 'base.html' %}
{% load static %}
{% block meta %}
<title>Add News</title>
{% endblock meta %}

{% block content %}

<div class="mt-20 form-container">
  <div class="form-header">Edit News</div>
  <form method="POST">
    {% csrf_token %}
    {{ form.non_field_errors }}

    {% for field in form %}
      <div class="form-group">
        <label class="form-label">{{ field.label }}:</label>
        {{ field }}
        {{ field.errors }}
      </div>
    {% endfor %}

    <button type="submit" class="submit-button">Edit News</button>
  </form>
</div>

{% endblock %}

news/templates/home_news.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Latest Game News from GameHunt</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}
{% block content %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 flex flex-col">
    <h1 class="text-5xl font-bold mb-4">News</h1>
    {% if role == 'admin' %}
    <div class="flex justify-end mb-6">
      <a href="{% url 'news:create_news' %}" class="styled-button">
        Add News
      </a>
    </div>
    {% endif %}

    <div id="news_cards"></div>
</div>
<script>
  async function getNews(){
      return fetch("{% url 'news:show_json' %}").then((res) => res.json())
  }

  async function refreshNews() {
    document.getElementById("news_cards").innerHTML = "";
    document.getElementById("news_cards").className = "";
    const newsEntries = await getNews();
    let htmlString = "";
    let classNameString = "";

    if (newsEntries.length === 0) {
        classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
        htmlString = `
            <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
                <img src="https://i.pinimg.com/564x/4e/6e/cf/4e6ecf90491e3eba4b368626eef09097.jpg" alt="Sad face" class="w-32 h-32 mb-4"/>
                <p class="text-center text-gray-600 mt-4">Slow news day...</p>
            </div>
        `;
    }
    else {
        classNameString = "columns-1 sm:columns-2 lg:columns-3 gap-6 space-y-6 w-full"
        newsEntries.forEach((item) => {
            const title = DOMPurify.sanitize(item.fields.title);
            const article = DOMPurify.sanitize(item.fields.article);
            const author = DOMPurify.sanitize(item.fields.author);
            htmlString += `
            <div class="relative break-inside-avoid" id="newsTableBody">
                <div class="max-w-3xl mx-auto bg-white rounded-lg shadow-lg p-3 flex items-center space-x-4 my-4">
                    <div class="flex-1 space-y-2">
                        <div class="flex justify-between items-center">
                            <a href="/news/${item.pk}" class="text-lg font-semibold text-gray-900 game-title-link hover:text-red-500">
                                ${title}
                            </a>
                        </div>

                        <p class="text-sm text-gray-600 line-clamp">
                        ${article}
                        </p>

                        <div class="flex justify-between text-xs text-gray-500">
                            <span>${author}</span>
                            <span>${item.fields.update_date}</span>
                        </div>

                    </div>

                </div>
            </div>
            `;
        });
    }
    document.getElementById("news_cards").className = classNameString;
    document.getElementById("news_cards").innerHTML = htmlString;
  }
  refreshNews();
  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

</script>
{% endblock content %}

news/templates/news.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{ title }}</title>
{% endblock meta %}
{% block content %}

<div class="flex flex-col min-h-screen mx-20 my-20">
  <div class="flex items-center space-x-2 my-2">
    <img src="https://cdn-icons-png.flaticon.com/512/109/109618.png" class="w-4 h-4">
    <a href="{% url 'news:home_news' %}" class="game-title-link">Back</a>
  </div>
  <h1 class="text-4xl w-3/5 font-bold">{{ title }}</h1>
  <div class="my-4 w-3/5 flex justify-between text-sm text-gray-500">
    <span>{{ author }}</span>
    <span>{{ update_date }}</span>
  </div>
  <p class="leading-loose w-3/5">{{ article }}</p>

</div>

<div class="w-4/12 grid columns-1 absolute mt-20 mx-10 right-0 top-3">
  <a href="{% url 'news:home_news' %}" class="font-bold text-xl game-title-link mb-4">Read more</a>
{% for news_entry in news_entries %}
{% if news_entry.id != pk  %}
  <div class="relative break-inside-avoid" id="newsTableBody">
    <div class="max-w-3xl mx-auto bg-white rounded-lg shadow-lg p-3 flex items-center space-x-4 my-4">
        <div class="flex-1 space-y-2">
            <div class="flex justify-between items-center">
              <a href="{% url 'news:show_news' news_entry.id %}" class="text-lg font-semibold text-gray-900 game-title-link hover:text-red-500">
                {{ news_entry.title }}
              </a>
            </div>
            
            <p class="text-sm text-gray-600 line-clamp">
            {{ news_entry.article }}
          </p>
          
          <div class="flex justify-between text-xs text-gray-500">
            <span>{{ news_entry.author }}</span>
            <span>{{ news_entry.update_date }}</span>
          </div>
        </div>
    </div>
  </div>
  {% endif %}
  {% endfor %}
</div>

{% if role == 'admin' %}
<div class="grid my-10 mx-10 w-fit columns-1 fixed bottom-0 left-0">
  <a class="my-4 edit-button" href="{% url 'news:edit_news' pk %}">Edit News</a>
  <a class="delete-button" href="{% url 'news:delete_news' pk %}">Delete News</a>
</div>
{% endif %}

{% endblock content %}