display/urls.py
from django.urls import path
from display.views import game_list, game_detail, add_comment_ajax, show_json_by_id, json_allcomments, delete_comment, create_comment_flutter, delete_comment_flutter

app_name = 'display'

urlpatterns = [
    path('list', game_list, name='game_list'),  # List of all games
    path('<uuid:id>/', game_detail, name='game_detail'),  # Detail for each game
    path('add-comment-ajax/<uuid:id>/', add_comment_ajax, name='add_comment_ajax'),  # Add comment via AJAX
    path('show-json/<uuid:id>/', show_json_by_id, name='show_json_by_id'),  # Show JSON data
    path('show-json-allcomments', json_allcomments, name='show_json_allcomments'),  # Show JSON data for all comments
    path('delete-comment/<str:id>/', delete_comment, name='delete_comment'),  # Delete a comment
    path('create-comment-flutter/', create_comment_flutter, name='create_comment_flutter'),  # Create a comment via Flutter
    path('delete-comment-flutter/<str:id>/', delete_comment_flutter, name='delete_comment_flutter'),  # Delete a comment via Flutter
]

gamehunt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('search.urls')),
    path('admin/', admin.site.urls),
    path('display/', include('display.urls')),
    path('search/', include('search.urls')),
    path('review/', include('review.urls')),
    path('news/', include('news.urls')),
    path('authentication/', include('authentication.urls')),
    path('userprofile/', include('userprofile.urls')),
    path('wishlist/', include('wishlist.urls')),
]

news/urls.py
from django.urls import path
from .views import show_news, edit_news, create_news, home_news, delete_news
from .views import show_xml, show_json, show_xml_by_id, show_json_by_id
from .views import create_news_flutter, edit_news_flutter, delete_news_flutter

app_name = 'news'

urlpatterns = [
    path('', home_news, name='home_news'),
    path('<uuid:id>', show_news, name='show_news'),
    path('create-news/', create_news, name='create_news'),
    path('edit-news/<uuid:id>', edit_news, name='edit_news'),
    path('delete/<uuid:id>', delete_news, name='delete_news'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('create-flutter/', create_news_flutter, name='create_news_flutter'),
    path('edit-flutter/<uuid:id>/', edit_news_flutter, name='edit_news_flutter'),
    path('delete-flutter/<uuid:id>/', delete_news_flutter, name='delete_news_flutter'),
]

search/urls.py
from django.urls import path
from search.views import show_search,show_json,delete_game,add_game_entry_ajax,show_json_by_id, edit_game_ajax,create_game_flutter, edit_game_flutter, delete_game_flutter, game_list_json,get_user_role

app_name = 'search'

urlpatterns = [
    path('', show_search, name='show_search'),
    path('json/', show_json, name='show_json'),
    path('delete/<uuid:id>', delete_game, name='delete_game'),
    path('create-game-entry-ajax', add_game_entry_ajax, name='add_game_entry_ajax'),
    path('json/<uuid:id>', show_json_by_id, name='show_json'),
    path('edit-game-ajax/<uuid:id>', edit_game_ajax, name = 'edit_game_ajax'),
    path('create-game-flutter/', create_game_flutter, name='create_mood_flutter'),
    path('edit-game-flutter/<uuid:game_id>/', edit_game_flutter, name='edit_game_flutter'),
    path('delete-game-flutter/<uuid:game_id>/', delete_game_flutter, name='delete_game_flutter'),
    path('search/json/', game_list_json, name='game_list_json'),
    path('user-role/', get_user_role, name='get_user_role'),
]

wishlist/urls.py
from django.urls import path
from wishlist.views import view_wishlist, delete_wishlist, create_wishlist, show_json, add_wishlist_ajax, get_wishlist_ajax, delete_wishlist_flutter

app_name = 'wishlist'

urlpatterns = [
    path('', view_wishlist, name='view_wishlist'),
    path('delete-wishlist/<uuid:id>/', delete_wishlist, name='delete_wishlist'),
    path('json/', show_json, name='show_json'),
    path('create-wishlist/<uuid:game_id>/', create_wishlist, name='create_wishlist'),
    path('add-wishlist-ajax/', add_wishlist_ajax, name='add_wishlist_ajax'),
    path('get-wishlist/', get_wishlist_ajax, name='get_wishlist'),
    path('delete-wishlist-flutter/<uuid:id>/', delete_wishlist_flutter, name='delete_wishlist_flutter')
]

display/models.py
from django.db import models
from search.models import Game
import uuid
 
class Comment(models.Model):
    game = models.ForeignKey(Game, related_name="comments", on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['created']

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.game)

display/forms.py
from django import forms
from display.models import Comment

class CommentForm(forms.ModelForm):
        
    class Meta:
        model = Comment
        fields = ["body"]
        widgets = {
            'body': forms.Textarea(attrs={
                'class': 'form-control',
                'rows': 3,
                'placeholder': 'Enter your comment here...'
            })
        }

display/views.py
from uuid import UUID
from django.shortcuts import get_object_or_404, render
from display.models import Comment
from display.forms import CommentForm
from search.models import Game
from django.shortcuts import render,redirect,reverse
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.core import serializers
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils import timezone
from django.utils.html import strip_tags
from django.contrib import messages
import json

# Create your views here.
def game_list(request):
    games = Game.objects.all()
    return render(request, 'game_list.html', {'games': games})

def game_detail(request, id):
    game=Game.objects.get(pk=id)
    comments = Comment.objects.filter(game=game).order_by('-id')

    if request.method == 'POST':
        comment_form = CommentForm(request.POST or None)
        if comment_form.is_valid():
            body = request.POST.get('body')
            comment = Comment.objects.create(game=game, name=request.user.username, body=body)
            comment.save()
            return HttpResponseRedirect(reverse('display:game_detail', args=[id]))
    else:
        comment_form = CommentForm()

    context = {'game': game, 
               'comments': comments, 
               'comment_form': comment_form}

    return render(request, 'game_detail.html', context)

def show_json_by_id(request, id):
    game = Game.objects.get(pk=id)
    data = Comment.objects.filter(game=game)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def json_allcomments(request):
    data = Comment.objects.all()
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

@csrf_exempt
@require_POST
def add_comment_ajax(request, id):
    # Extract the comment body from the POST request
    body = request.POST.get("body")
    name = request.user.username
    game = Game.objects.get(pk=id)
    created = timezone.now()
    formatted_created = created.strftime("%B %d, %Y, %I:%M %p")
    
    # Create a new Comment object and save it to the database
    new_comment = Comment(
        game=game,
        body=body, 
        name=name,
        created=formatted_created
    )
    new_comment.save()

    return HttpResponse(b"CREATED", status=201)

def delete_comment(request, id):
    # Get game berdasarkan id
    comment = Comment.objects.get(pk=id)
    # Hapus game
    comment.delete()
    # Kembali ke halaman awal
    return HttpResponseRedirect(reverse('display:game_detail', args=[comment.game.id]))

@csrf_exempt
def create_comment_flutter(request):   
    if request.method == 'POST':

        data = json.loads(request.body)
        new_comment = Comment.objects.create(
            name=request.user.username,
            body=data['body'],
            game=Game.objects.get(pk=data['game']),
            created=timezone.now()
        )

        new_comment.save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

@csrf_exempt
def delete_comment_flutter(request, id):
    if request.method == 'DELETE':
        try:
            # news_uuid = UUID(news_id)
            comment = Comment.objects.get(pk=id)
            comment.delete()
            return JsonResponse({"status": "success"}, status=200)
        except Comment.DoesNotExist:
            return JsonResponse({"status": "error", "message": "News not found"}, status=404)
        except Exception as e:
            return JsonResponse({"status": "error", "message": str(e)}, status=500)
    else:
        return JsonResponse({"status": "error", "message": "Invalid request method"}, status=405)

display/templates/card_comment.html
<div class="bg-white rounded-xl overflow-hidden shadow-xl hover:shadow-2xl transition duration-300">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-red-500">{{ name }}</h5>
      <p class="text-red">{{ body }}</p>
      <p class="text-red">Posted on {{ time }}</p>
    </div>
</div>

display/templates/card_detail.html
<div class="bg-white rounded-xl border border-gray-300 overflow-hidden shadow-xl hover:shadow-2xl transition duration-300">
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-semibold text-red-500">{{ title }}</h5>
      <p class="text-red">{{ value }}</p>
    </div>
</div>

display/templates/card_store.html
<div class="flex rounded-xl overflow-hidden shadow-xl border border-gray-300 hover:shadow-2xl transition duration-300">
    <div class="left-column">
        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor" class="location-icon" width="40" height="40">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 2c-4.418 0-8 3.582-8 8 0 4.418 8 12 8 12s8-7.582 8-12c0-4.418-3.582-8-8-8z" />
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 11a1 1 0 100-2 1 1 0 000 2z" />
        </svg>
        <p class="label text-center">Available Store</p>
    </div>
    <div class="right-column">
        <p class="store">{{ store }}</p>
        <p class="address">{{ address }}</p>
    </div>
</div>

display/templates/game_detail.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>{{ game.name }} Details</title>
<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}

<!-- Container for the entire game details section -->
<section class="container mx-auto p-6 pt-24 justify-center items-center">
    <div class="flex flex-col bg-white shadow-2xl rounded-3xl p-6 max-w-3xl mx-auto relative">
        <div class="flex flex-col items-center md:flex-row">
             <!-- Game Cover Image -->
            <div class="mt-4 md:ml-4">
                <img src="{% static 'image/logo.png' %}" alt="Logo" class="w-40 h-40 rounded-xl shadow-xl bg-red-500">
            </div>
        
            <!-- Content -->
            <div class="mt-4 text-center md:ml-6 md:text-left">
                <!-- Game Title and Info -->
                <h1 class="mb-2 text-4xl font-bold">{{ game.name }}</h1>
                <div class="flex items-center justify-center md:justify-left space-x-2 text-sm text-gray-500">
                    <!-- Rating -->
                    <div class="bg-red-500 text-white px-2 py-1 rounded-md font-semibold">
                        {{ game.ratings }}
                    </div>
                    <!-- Developer and Publisher -->
                    <p class="text-blue-500 font-semibold">{{ game.developer }}</p>
                    <span>•</span>
                    <p class="text-blue-500 font-semibold">{{ game.genre }}</p>
                    <span>•</span>
                    <!-- Release Date -->
                    <span>{{ game.year }}</span>
                </div>
            </div>
        </div>
            
        <!-- Wishlist Button -->
        <div class="flex flex-col justify-end md:flex-row mt-6">
            <a href="/review/show_reviews/{{ game.pk }}" class="flex items-center justify-center bg-yellow-300 text-white px-4 py-3 mb-2 rounded-md font-semibold md:mr-2 hover:bg-yellow-400 transition duration-300 md:w-1/4">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2"></polygon>
                </svg>
                <span>See Reviews</span>
            </a>
            <a href="{% url 'wishlist:create_wishlist' game_id=game.id %}" class="flex items-center justify-center bg-blue-600 text-white px-4 py-3 mb-2 rounded-md font-semibold hover:bg-blue-700 transition duration-300 md:w-1/4">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 mr-2" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.35l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"></path>
                </svg>
                <span>Wishlist</span>
            </a>
        </div>
    </div>

    <div class="flex flex-col justify-center md:flex-row min-h-screen md:space-x-10 space-y-6 md:space-y-0">
        <!-- Game details section -->
        <div class="mt-12 w-full md:w-3/5 space-y-6">
            <!-- Individual details using card_detail.html -->
            {% include "card_detail.html" with title='Description' value=game.description %}
            {% include "card_detail.html" with title='Ratings' value=game.ratings %}
            {% include "card_detail.html" with title='Price' value=game.harga %}
            {% include "card_detail.html" with title='Developer' value=game.developer %}
            {% include "card_detail.html" with title='Genre' value=game.genre %}
            {% include "card_detail.html" with title='Year' value=game.year %}
            {% include "card_store.html" with store=game.toko1 address=game.alamat1 %}
            {% if game.toko2 %}
                {% include "card_store.html" with store=game.toko2 address=game.alamat2 %}
            {% endif %}
            {% if game.toko3 %}
                {% include "card_store.html" with store=game.toko3 address=game.alamat3 %}
            {% endif %}
        </div>
    </div>

    <!-- Back to Game List button -->
    <div class="flex justify-center mt-12">
        <a href="{% url 'search:show_search' %}" class="edit-button">
            Back to Game List
        </a>
    </div>

    <!-- Comments Section -->
    <div class="flex flex-col mx-auto w-full md:w-1/2">
        
        <form id="commentForm">
            {% csrf_token %}
            <div class="w-full mx-auto mt-4">
                <label for="body" class="text-left text-black text-4xl font-bold mt-4">Comments</label>
                <textarea 
                id="body" name="body" rows="3"
                placeholder="Enter your comment here..." 
                class="w-full border border-gray-300 rounded-md p-2 mt-4 focus:outline-none resize-none"
                required></textarea>
            </div>
    
            <div class="flex justify-end">
                <button type="submit" id="commentButton" class="w-1/5 edit-button justify-end" onclick="addComment()">Post</button>
            </div>
        </form>

        <!-- Comments From AJAX -->
        <div id="comment_card"></div>
        
    </div>

    <div class="flex justify-center mt-12">
        <p class="text-gray-500 text-sm">© 2024 GameHunt. All rights reserved.</p>
    </div>
</section>

<script>
    // ===========================POSTAJAX========================================
    function addComment() {
        fetch("{% url 'display:add_comment_ajax' id=game.id %}", {
            method: "POST",
            body: new FormData(document.querySelector('#commentForm')),
        })
        .then(response => {refreshComments();})
        
        return false;
    }


  //============================GETAJAX========================================
  
  async function getComments(){
    return fetch("{% url 'display:show_json_by_id' id=game.id %}").then((res) => res.json())
  }

  async function refreshComments() {
  const commentsContainer = document.getElementById("comment_card");
  commentsContainer.innerHTML = "";
  const comments = await getComments();

  let htmlString = "";
  const currentUser = "{{ user.username }}";
  if (comments.length === 0) {
    htmlString = '<p class="text-center">No comments yet.</p>';
  } else {
    comments.forEach((item) => {
        const name = DOMPurify.sanitize(item.fields.name);
        const body = DOMPurify.sanitize(item.fields.body);
        const created = DOMPurify.sanitize(item.fields.created);
      htmlString += `
        <div class="bg-white rounded-xl border border-grey-300 mt-2 overflow-hidden shadow-xl hover:shadow-2xl transition duration-300">
            <div class="p-4 animate-shine">
                <h5 class="text-sm font-semibold text-blue-500">${name}</h5>
                <p class="text-red">"${body}"</p>
                <p class="text-yellow-600 text-sm">Posted on ${created}</p>
            </div>
            ${currentUser === item.fields.name ? `
            <div class="flex justify-end mr-2 mb-2">
                <a href="/display/delete-comment/${item.pk}/">
                <button class="delete-button">Delete</button>
                </a>
            </div>
            ` : ''}
        </div>      
        `;
    });
  }

  commentsContainer.innerHTML = htmlString;
}

refreshComments();
</script>
{% endblock content %}

display/templates/game_list.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Game List</title>
{% endblock meta %}

{% block content %}
<div class="mt-16">
        {% for game in games %}
            <p class="text-black">
                {{ game.name }} - {{ game.genre }} ({{ game.year }})
                <a href="{% url 'display:game_detail' game.id %}">View Details</a>
            </li>
        {% endfor %}
</div>

{% endblock content %}